version: '3'
services:
  agro_info_user:
    build:
      context: ./frontUser
      dockerfile: Dockerfile.serve
    container_name: agro_info_user
    environment:
      - REACT_APP_NOT_SECRET_CODE=http://127.0.0.1:${BACK_PORT}
    ports:
      - ${USER_FRONT_EXPOSE}:${USER_FRONT_PORT}
    networks:
      - main_network

  agro_info_admin:
    build:
      context: ./frontAdmin
      dockerfile: Dockerfile.serve
    container_name: agro_info_admin
    environment:
      - REACT_APP_NOT_SECRET_CODE=http://127.0.0.1:${BACK_PORT}
    ports:
      - ${ADMIN_FRONT_EXPOSE}:${ADMIN_FRONT_PORT}
    networks:
      - main_network

networks:
  main_network:
    external: true