version: '3'
services:
  agro_info_back:
    build:
      context: ./back
    restart: always
    container_name: agro_info_back
    environment:
      - DB_URL=mongodb://mongodb:27017/agro_info
      - PORT=${PORT}
    ports:
      - ${EXPOSE}:${PORT}
    networks:
      - main_network

networks:
  main_network:
    external: true